import { MIND_CLAIM_RISK_BRIEF_CONTRACT_VERSION } from "@/lib/review/mind-claim-intelligence-constants";
import type { MindClaimRiskBriefOutput } from "@/lib/watch/mind-claim-risk-brief-contract";

export const MIND_CLAIM_RISK_BRIEF_DEMO_FIXTURE_CONTRACT_VERSION =
  MIND_CLAIM_RISK_BRIEF_CONTRACT_VERSION;

const DEMO_DATE = "2026-06-24";

const DEMO_COST_REPORT: MindClaimRiskBriefOutput["cost_report"] = {
  reported_by_mind: false,
  summary: "Non-live fixture response (no external Mind call or PubMed retrieval).",
  search_count: 0,
  abstracts_fetched: 0,
};

const DEMO_SEARCH_CAPABILITY =
  "This is a controlled validation fixture risk brief response for operator validation workflow. No live PubMed or external evidence retrieval was performed.";

const DEMO_LIMITATIONS =
  "Controlled validation fixture only. This response was not generated by live Mind evidence retrieval and must not be treated as a real PubMed search result.";

const KEY_EVIDENCE_RISK_INSIGHT =
  "oral magnesium evidence ≠ topical magnesium evidence ≠ branded ritual evidence";

function buildStressHormonesFixture(claimText: string): MindClaimRiskBriefOutput {
  return {
    contract_version: MIND_CLAIM_RISK_BRIEF_DEMO_FIXTURE_CONTRACT_VERSION,
    claim_text: claimText,
    source_context: "Magnesium Calm Ritual spa treatment copy",
    search_capability_statement: DEMO_SEARCH_CAPABILITY,
    searches_performed: [
      {
        source: "PubMed",
        query: "magnesium stress cortisol randomized controlled trial",
        date_performed: DEMO_DATE,
        results_summary:
          "Oral magnesium supplementation studies show mixed effects on subjective stress; cortisol endpoints are inconsistent.",
      },
      {
        source: "PubMed",
        query: "cortisol reduction wellness intervention",
        date_performed: DEMO_DATE,
        results_summary:
          "General wellness and relaxation interventions may affect perceived stress; direct cortisol reduction evidence is limited.",
      },
      {
        source: "PubMed",
        query: "stress hormones topical magnesium transdermal",
        date_performed: DEMO_DATE,
        results_summary:
          "Very limited peer-reviewed evidence for transdermal magnesium effects on stress hormone biomarkers.",
      },
      {
        source: "PubMed",
        query: "topical transdermal magnesium absorption skin",
        date_performed: DEMO_DATE,
        results_summary:
          "Transdermal magnesium absorption and systemic bioavailability remain debated; evidence is indirect.",
      },
      {
        source: "PubMed",
        query: "spa massage aromatherapy cortisol adrenaline ritual",
        date_performed: DEMO_DATE,
        results_summary:
          "Massage and spa treatments may reduce perceived stress; biomarker evidence for branded rituals is sparse.",
      },
    ],
    evidence_found: [
      {
        title: "Oral magnesium supplementation and stress in adults: a systematic review",
        authors: "Demo Author et al.",
        journal: "Demo Journal of Nutritional Science",
        year: "2022",
        pmid: "35000001",
        doi: "10.1000/demo.oral.magnesium",
        url: "https://pubmed.ncbi.nlm.nih.gov/35000001/",
        evidence_category: "ingredient",
        relevance_to_claim: "indirect",
        summary:
          "Oral magnesium may support subjective stress measures in some populations; does not establish topical or ritual-specific hormone reduction.",
      },
      {
        title: "Transdermal magnesium: limited evidence for systemic effects",
        authors: "Demo Research Group",
        journal: "Demo Dermatology Reports",
        year: "2021",
        pmid: "35000002",
        doi: "10.1000/demo.transdermal",
        url: "https://pubmed.ncbi.nlm.nih.gov/35000002/",
        evidence_category: "delivery_route",
        relevance_to_claim: "weak",
        summary:
          "Topical magnesium evidence focuses on skin delivery, not cortisol or adrenaline reduction as claimed.",
      },
      {
        title: "Massage therapy and cortisol: mixed biomarker outcomes",
        authors: "Demo Spa Science Lab",
        journal: "Demo Complementary Therapies",
        year: "2020",
        pmid: "35000003",
        doi: "10.1000/demo.massage.cortisol",
        url: "https://pubmed.ncbi.nlm.nih.gov/35000003/",
        evidence_category: "treatment",
        relevance_to_claim: "indirect",
        summary:
          "General massage may affect cortisol in some settings; does not validate a branded magnesium spa ritual claim.",
      },
    ],
    evidence_not_found: [
      {
        gap: "No direct evidence for Magnesium Calm Ritual as a branded treatment reducing stress hormones.",
        importance:
          "Branded ritual evidence cannot be inferred from generic magnesium or massage literature.",
      },
      {
        gap: "No strong direct evidence that topical or transdermal magnesium reduces stress hormones.",
        importance:
          "Delivery-route evidence must be distinguished from oral magnesium and from experiential claims.",
      },
      {
        gap: "No direct evidence that the full spa ritual reduces cortisol or adrenaline as claimed.",
        importance:
          "Composite ritual outcomes cannot be assumed from ingredient or single-modality studies.",
      },
    ],
    evidence_posture: "weak_indirect",
    evidence_strength: "low",
    risk_level: "high",
    regulatory_sensitivity: "high",
    key_evidence_risk_insight: KEY_EVIDENCE_RISK_INSIGHT,
    safer_wording: "designed to support relaxation and a calmer state",
    operator_recommendation: "soften",
    limitations: DEMO_LIMITATIONS,
    cost_report: DEMO_COST_REPORT,
  };
}

function buildSleepFixture(claimText: string): MindClaimRiskBriefOutput {
  return {
    contract_version: MIND_CLAIM_RISK_BRIEF_DEMO_FIXTURE_CONTRACT_VERSION,
    claim_text: claimText,
    source_context: "Spa wellness treatment copy",
    search_capability_statement: DEMO_SEARCH_CAPABILITY,
    searches_performed: [
      {
        source: "PubMed",
        query: "magnesium sleep quality randomized trial",
        date_performed: DEMO_DATE,
        results_summary:
          "Oral magnesium may modestly support sleep quality in some adults; spa ritual context not established.",
      },
      {
        source: "PubMed",
        query: "relaxation treatment deep sleep support",
        date_performed: DEMO_DATE,
        results_summary:
          "Relaxation interventions can improve subjective sleep; direct deep-sleep biomarker evidence is limited.",
      },
      {
        source: "PubMed",
        query: "spa aromatherapy sleep outcomes",
        date_performed: DEMO_DATE,
        results_summary:
          "Aromatherapy and spa treatments show mixed sleep-related subjective outcomes.",
      },
    ],
    evidence_found: [
      {
        title: "Magnesium supplementation and subjective sleep quality: a meta-analysis",
        authors: "Demo Sleep Research Consortium",
        journal: "Demo Sleep Medicine Reviews",
        year: "2023",
        pmid: "36000001",
        doi: "10.1000/demo.magnesium.sleep",
        url: "https://pubmed.ncbi.nlm.nih.gov/36000001/",
        evidence_category: "ingredient",
        relevance_to_claim: "indirect",
        summary:
          "Oral magnesium evidence for sleep does not establish a branded spa ritual deep-sleep claim.",
      },
    ],
    evidence_not_found: [
      {
        gap: "No direct evidence that this branded spa ritual supports deep sleep as claimed.",
        importance: "Treatment-level evidence cannot be assumed from ingredient sleep literature.",
      },
      {
        gap: "No strong evidence linking topical magnesium application to deep sleep outcomes.",
        importance: "Delivery route must be distinguished from oral supplementation evidence.",
      },
    ],
    evidence_posture: "weak_indirect",
    evidence_strength: "low",
    risk_level: "medium",
    regulatory_sensitivity: "medium",
    key_evidence_risk_insight: KEY_EVIDENCE_RISK_INSIGHT,
    safer_wording: "designed to support a relaxing pre-sleep ritual",
    operator_recommendation: "soften",
    limitations: DEMO_LIMITATIONS,
    cost_report: DEMO_COST_REPORT,
  };
}

function buildGenericWellnessFixture(claimText: string): MindClaimRiskBriefOutput {
  return {
    contract_version: MIND_CLAIM_RISK_BRIEF_DEMO_FIXTURE_CONTRACT_VERSION,
    claim_text: claimText,
    source_context: "General wellness spa copy",
    search_capability_statement: DEMO_SEARCH_CAPABILITY,
    searches_performed: [
      {
        source: "PubMed",
        query: "spa wellness relaxation treatment outcomes",
        date_performed: DEMO_DATE,
        results_summary:
          "Spa and relaxation treatments may improve subjective wellness; claim-specific evidence varies.",
      },
      {
        source: "PubMed",
        query: "magnesium wellness ritual experiential claims",
        date_performed: DEMO_DATE,
        results_summary:
          "Limited direct evidence for branded wellness ritual claims.",
      },
    ],
    evidence_found: [
      {
        title: "Wellness spa treatments and perceived relaxation: observational review",
        authors: "Demo Wellness Institute",
        journal: "Demo Integrative Health",
        year: "2022",
        pmid: "37000001",
        doi: "10.1000/demo.wellness.spa",
        url: "https://pubmed.ncbi.nlm.nih.gov/37000001/",
        evidence_category: "treatment",
        relevance_to_claim: "indirect",
        summary:
          "General relaxation benefits are plausible; specific branded ritual claims need separate substantiation.",
      },
    ],
    evidence_not_found: [
      {
        gap: "No direct evidence for this specific branded ritual claim.",
        importance: "Generic wellness evidence does not substitute for claim-specific support.",
      },
    ],
    evidence_posture: "weak_indirect",
    evidence_strength: "low",
    risk_level: "medium",
    regulatory_sensitivity: "medium",
    key_evidence_risk_insight: KEY_EVIDENCE_RISK_INSIGHT,
    safer_wording: "designed to support a relaxing wellness experience",
    operator_recommendation: "soften",
    limitations: DEMO_LIMITATIONS,
    cost_report: DEMO_COST_REPORT,
  };
}

export function selectMindClaimRiskBriefDemoFixture(
  claimText: string
): MindClaimRiskBriefOutput {
  const normalized = claimText.toLowerCase();

  if (normalized.includes("reduce stress hormones")) {
    return buildStressHormonesFixture(claimText);
  }

  if (normalized.includes("support deep sleep")) {
    return buildSleepFixture(claimText);
  }

  return buildGenericWellnessFixture(claimText);
}

export function buildMindClaimRiskBriefDemoFixtureResponseText(claimText: string): string {
  return JSON.stringify(selectMindClaimRiskBriefDemoFixture(claimText));
}
